[colors]
background = '#111416'
foreground = '#e1e2e6'

cursor_bg = '#98ccf6'
cursor_fg = '#111416'
cursor_border = '#98ccf6'

selection_bg = '#6599c0'
selection_fg = '#e1e2e6'

ansi = ['#111416', '#ff729d', '#7bf68a', '#fff772', '#7eb9e9', '#224e71', '#98ccf6', '#eff8ff']
brights = ['#939a9f', '#ff9fbc', '#a5ffb1', '#fffaa5', '#acd9ff', '#bae0ff', '#d3ebff', '#f8fcff']
